# Generated by Django 3.1.7 on 2021-04-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotfinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parkinglot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthlyrent', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='pics')),
                ('gmaplink', models.CharField(max_length=150)),
                ('verifystatus', models.BooleanField(default=False)),
            ],
        ),
    ]
