# Generated by Django 3.1.7 on 2021-04-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotfinder', '0003_auto_20210402_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=30)),
            ],
        ),
    ]
