# Generated by Django 3.1.7 on 2021-05-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotfinder', '0006_auto_20210518_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='activestatus',
            field=models.BooleanField(default=True),
        ),
    ]
