# Generated by Django 3.1.7 on 2021-05-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotfinder', '0007_parkinglot_activestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotverification',
            name='allotedstatus',
            field=models.BooleanField(default=True),
        ),
    ]
