# Generated by Django 3.1.7 on 2021-05-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotfinder', '0008_lotverification_allotedstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotverification',
            name='feedback',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lotverification',
            name='verifydate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
