# Generated by Django 3.1.7 on 2021-06-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotfinder', '0010_booking_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='bookedstatus',
            field=models.BooleanField(default=False),
        ),
    ]
