# Generated by Django 3.1.7 on 2021-06-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotfinder', '0012_auto_20210601_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='monthlysubscribe',
            field=models.BooleanField(default=False),
        ),
    ]
