# Generated by Django 3.1.7 on 2021-06-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotfinder', '0014_auto_20210622_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='pendingconfirm',
            field=models.BooleanField(default=False),
        ),
    ]
